#!/usr/bin/env python

import os
from redis import Redis

def is_alive(pid):
    try:
        os.kill(pid, 0)
        return True
    except OSError, e:
        if e.errno == 3: return False
        elif e.errno == 1: return True #permission denied
        else: raise e

def main():
    from optparse import OptionParser
    usage = "usage: %prog [options]"
    parser = OptionParser(usage)
    parser.add_option("--host", dest="host", default="localhost")
    parser.add_option("--port",dest="port",type="int", default=6379)
    (options,args) = parser.parse_args()
        
    hostname = os.uname()[1]
    r = Redis(options.host,options.port)
    
    keys = r.keys("resque:worker:%s:*" % hostname)
    pids = [(int(k.split(":")[3]), k) for k in keys]
    for pid, key in pids:
        if not is_alive(pid):
            print "worker", key, "is dead, deleting key"
            r.delete(key)
            
    keys = r.keys("resque:stat:%s:*" % hostname)
    pids = [(int(k.split(":")[4]), k) for k in keys if len(k.split(":"))==6]
    for pid, key in pids:
        if not is_alive(pid):
            print "worker stat", key, "is dead, deleting key"
            r.delete(key)
    
    keys = r.smembers("resque:workers")
    pids = [(int(k.split(":")[1]), k.split(":")[0], k) for k in keys]
    for pid, hname, key in pids:
        if not is_alive(pid) and hname==hostname:       
            print "worker", key, "is dead, remove from worker set"
            r.srem('resque:workers', key)
        
if __name__ == "__main__":
    main()